import { StyleSheet } from "react-native";

export const colors = {
 
  primary: "#1f2937",        
  primaryLight: "#4b5563",  
  primaryDark: "#111827",    
  secondary: "#374151",      
  success: "#10b981",        
  successLight: "#d1fae5",   
  danger: "#ef4444",       
  dangerLight: "#fef2f2",  
  background: "#f3f4f6",   
  surface: "#ffffff",       
  border: "#e5e7eb",         
  textPrimary: "#000000",   
  textSecondary: "#6b7280",  
  textTertiary: "#9ca3af",   
  authentic: "#22c55e",      
  authenticBg: "#f0fdf4",    
  ai: "#ef4444",             
  aiBg: "#fef2f2",          
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  logoutButton: {
    position: "absolute",
    top: 20,
    right: 20,
    zIndex: 1000,
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  content: {
    padding: 20,
  },
  heroSection: {
    marginBottom: 40,
    marginTop: 60,
    alignItems: "center",
  },
  heroTitle: {
    fontSize: 36,
    fontWeight: "bold",
    color: colors.textPrimary,
    marginBottom: 12,
    textAlign: "center",
  },
  heroSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: "center",
  },
  header: {
    marginBottom: 30,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: colors.textPrimary,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  inputSection: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 8,
  },
  labelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  errorText: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.danger,
    opacity: 0.7,
  },
  inputContainer: {
    flexDirection: "row",
    gap: 10,
  },
  input: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  mainInputCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  mainInput: {
    fontSize: 16,
    color: colors.textPrimary,
    paddingVertical: 12,
    marginBottom: 16,
  },
  platformTagsInline: {
    flexDirection: "row",
    gap: 8,
  },
  tagSmall: {
    backgroundColor: "#f3f4f6",
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tagSmallText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  pasteButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingHorizontal: 20,
    justifyContent: "center",
  },
  pasteButtonText: {
    color: colors.surface,
    fontWeight: "600",
  },
  analyzeButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: 18,
    alignItems: "center",
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "center",
  },
  analyzeButtonDisabled: {
    backgroundColor: colors.textTertiary,
    opacity: 0.6,
  },
  analyzeButtonText: {
    color: colors.surface,
    fontSize: 18,
    fontWeight: "600",
  },
  historyButton: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 18,
    alignItems: "center",
    borderWidth: 2,
    borderColor: colors.primary,
    marginBottom: 30,
  },
  historyButtonText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: "600",
  },
  infoSection: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 12,
  },
  infoText: {
    fontSize: 15,
    color: colors.textSecondary,
    lineHeight: 24,
  },
  supportedPlatforms: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 20,
  },
  platformsTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 12,
  },
  platformTags: {
    flexDirection: "row",
    gap: 10,
  },
  tag: {
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tagText: {
    color: colors.textPrimary,
    fontWeight: "600",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  loadingText: {
    fontSize: 20,
    fontWeight: "600",
    color: colors.textPrimary,
    marginTop: 20,
  },
  loadingSubtext: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 8,
    textAlign: "center",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },

  resultCard: {
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    marginBottom: 20,
  },
  aiDetected: {
    backgroundColor: colors.aiBg,
    borderWidth: 2,
    borderColor: colors.ai,
  },
  authentic: {
    backgroundColor: colors.authenticBg,
    borderWidth: 2,
    borderColor: colors.authentic,
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 8,
  },
  confidenceText: {
    fontSize: 18,
    color: colors.textSecondary,
  },
  detailsCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 16,
  },
  metricRow: {
    marginBottom: 16,
  },
  metricLabel: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  progressBar: {
    height: 8,
    backgroundColor: colors.border,
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 4,
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.primary,
  },
  metricValue: {
    fontSize: 12,
    color: colors.textTertiary,
    textAlign: "right",
  },
  explanationCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  explanationText: {
    fontSize: 15,
    color: colors.textPrimary,
    lineHeight: 24,
  },
  newAnalysisButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: 18,
    alignItems: "center",
  },
  newAnalysisButtonText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: "600",
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  emptyText: {
    fontSize: 18,
    color: colors.textSecondary,
    marginBottom: 20,
  },
  startButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  startButtonText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: "600",
  },
  list: {
    flex: 1,
  },
  dateHeader: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginTop: 8,
    borderBottomWidth: 2,
    borderBottomColor: colors.primary,
    marginBottom: 12,
  },
  dateHeaderText: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.primary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 12,
    marginHorizontal: 20,
    marginBottom: 12,
    overflow: "hidden",
  },
  historyItemContent: {
    flex: 1,
    padding: 16,
  },
  deleteIconButton: {
    padding: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  historyItemNew: {
    backgroundColor: colors.successLight,
    shadowColor: colors.success,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  historyTime: {
    fontSize: 24,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  historyBadgeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
    fontSize: 12,
    fontWeight: "600",
  },
  aiBadge: {
    backgroundColor: colors.aiBg,
    color: colors.ai,
  },
  authenticBadge: {
    backgroundColor: colors.authenticBg,
    color: colors.authentic,
  },
  confidence: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  url: {
    fontSize: 14,
    color: colors.textPrimary,
    marginBottom: 4,
  },
  urlSecondary: {
    fontSize: 12,
    color: colors.textTertiary,
    fontStyle: "italic",
  },
  timestamp: {
    fontSize: 12,
    color: colors.textTertiary,
  },
  clearButton: {
    margin: 20,
    backgroundColor: colors.danger,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  clearButtonText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: "600",
  },

  scrollContent: {
    flexGrow: 1,
    padding: 24,
    justifyContent: "center",
  },

  appName: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primary,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 12,
  },

  form: {
    marginBottom: 24,
  },
  inputGroup: {
    marginBottom: 20,
  },

  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 16,
  },
  passwordContainerError: {
    borderColor: colors.danger,
    borderWidth: 2,
  },
  passwordInput: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 16,
    color: colors.textPrimary,
  },
  eyeIcon: {
    padding: 4,
  },
  forgotPassword: {
    alignSelf: "flex-end",
    marginTop: 8,
  },
  forgotPasswordText: {
    color: colors.primary,
    fontWeight: "500",
    fontSize: 14,
  },
  loginButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  loginButtonText: {
    color: colors.surface,
    fontSize: 18,
    fontWeight: "600",
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border,
  },
  dividerText: {
    marginHorizontal: 16,
    color: colors.textTertiary,
    fontWeight: "500",
  },
  googleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 16,
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
  },
  footerText: {
    color: colors.textSecondary,
    fontSize: 15,
  },
  signUpLink: {
    color: colors.primary,
    fontWeight: "600",
    fontSize: 15,
  },

  // Centered Login Layout
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  loginContainer: {
    width: "100%",
    maxWidth: 440,
  },
  loginHeader: {
    marginBottom: 40,
    alignItems: "center",
  },
  loginTitle: {
    fontSize: 32,
    fontWeight: "bold",
    color: colors.textPrimary,
    marginBottom: 12,
    textAlign: "center",
  },
  loginSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: "center",
  },
  loginForm: {
    marginBottom: 24,
  },
  loginFooter: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
  },

  signupScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  signupContainer: {
    width: "100%",
    maxWidth: 440,
  },
  signupHeader: {
    marginBottom: 40,
    alignItems: "center",
  },
  signupTitle: {
    fontSize: 32,
    fontWeight: "bold",
    color: colors.textPrimary,
    marginBottom: 12,
    textAlign: "center",
  },
  signupSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: "center",
  },
  signupForm: {
    marginBottom: 24,
  },
  signupFooter: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
  },

  button: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    color: colors.surface,
    fontSize: 18,
    fontWeight: "600",
  },

  loginLink: {
    color: colors.primary,
    fontWeight: "600",
    fontSize: 15,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    marginTop: -60,
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primaryLight + "33", // 20% opacity
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: colors.textPrimary,
    marginBottom: 8,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: "center",
    marginBottom: 32,
    lineHeight: 24,
    maxWidth: 260,
  },
  analysisSection: {
    marginTop: 20,
    marginBottom: 20,
  },
  analysisSectionTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 16,
  },
  loadingCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 32,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  errorCard: {
    backgroundColor: colors.dangerLight,
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.danger,
  },
  resultHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: 12,
  },
  resultUrl: {
    fontSize: 14,
    color: colors.textPrimary,
    marginBottom: 8,
  },
  tapToView: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
    marginTop: 4,
  },
  deleteButton: {
    backgroundColor: colors.danger,
    justifyContent: "center",
    alignItems: "flex-end",
    marginHorizontal: 20,
    marginBottom: 12,
    borderRadius: 12,
    overflow: "hidden",
  },
  deleteButtonInner: {
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    height: "100%",
  },
  deleteButtonText: {
    color: colors.surface,
    fontWeight: "600",
    fontSize: 16,
  },
  toast: {
    position: "absolute",
    bottom: 30,
    left: 20,
    right: 20,
    backgroundColor: colors.textPrimary,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  toastText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: "500",
  },
});
